theme = "gruvbox_transparent"

# [#2869]
# icons = "nerd"
# icons = "nerdfonts"

# [editor.icons]
# bufferline = true
# picker = true
# statusline = true

# [editor.explorer]
# position = "left"
# column-width = 30

[editor]
color-modes = true
cursorline = true
cursorcolumn = false
auto-info = true
auto-completion = true
true-color = true
undercurl = true
line-number = "relative"
mouse = true
bufferline = "always"
idle-timeout = 0

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.file-picker]
hidden = false

[editor.soft-wrap]
enable = true

[editor.statusline]
left = [
    "mode",
    "spacer",
    "spinner",
    "spacer",
    "version-control",
    "spacer",
    "file-name",
    "file-modification-indicator",

]
center = ["diagnostics", "workspace-diagnostics"]
right = [
    "selections",
    "primary-selection-length",
    "position",
    "position-percentage",
    "file-encoding",
    "file-line-ending",
    "file-type",
]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
snippets = true
display-messages = true


[editor.indent-guides]
render = true
character = "┊" # Some characters that work well: "▏", "╎", "┆", "┊"
skip-levels = 0


[keys.insert]
A-q = "normal_mode"
C-h = "goto_line_start"
C-l = "goto_line_end"
A-j = "move_line_down"
A-k = "move_line_up"
A-h = "move_char_left"
A-l = "move_char_right"
A-w = "move_next_word_start"
A-b = "move_prev_word_start"
A-e = "move_next_word_end"
A-a = "open_above"
A-o = "open_below"
A-p = "paste_after"
A-u = "half_page_up"
A-d = "half_page_down"
A-x = "delete_char_backward"
A-f = "delete_char_forward"
C-x = "delete_word_backward"
C-f = "delete_word_forward"
